### ISSUE TITLE
`arg` & `entrypoint` keyword placement

### ISSUE THREAD

**Issue by wei** [actions/migrate#27]
Taking the example from README.md:

```hcl
workflow "on push" {
    on = "push"
    resolves = ["say hi"]
}

action "say hi" {
    uses = "docker/whalesay@master"
    runs = "cowsay hello actions"
}
```

Result:
```
on: push
name: on push
jobs:
  sayHi:
    name: say hi
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: say hi
      uses: docker/whalesay@master
      with:
        entrypoint: cowsay
        args: hello actions
```

My question is around [args](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsargs) and [entrypoint](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsentrypoint) keywords being under [with](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepswith). In the documentation linked, args and entrypoint should be right under `jobs.<job_id>.steps`, is there a reason for them to be placed under `jobs.<job_id>.steps.with`?
