### ISSUE TITLE
Unable to pull private Docker images for use by later steps

### ISSUE THREAD

**Issue by aidansteele** [actions/migrate#29]
Using the HCL syntax, I had an action like this:

```hcl
action "Pull build env" {
  uses = "docker://glassechidna/github-action-aws"
  secrets = ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"]
  runs = "./pullbuildenv.sh"
}
```

It would use these credentials to authenticate to AWS ECR and pull a Docker image from a private image repository. This image could then be used in later steps, e.g:

```hcl
action "Test" {
  needs = ["Pull build env"]
  uses = "docker://01234567890.dkr.ecr.us-east-1.amazonaws.com/private-image:latest"
  args = "go test -short ./..."
}
```

This no longer appears to be possible as the new style GitHub Actions attempts to pull _all_ images (specified by `uses: docker://...` in the YAML) at the start of the code -- before my login step has had a chance to run.

Is supporting private images on the roadmap for GitHub Actions? I'd be happy to use Docker Hub, GCR, ECR, etc - whatever it takes. Support could take the form of "standard" secret names that are used to login to Docker Hub / ECR when present.

**Comment by aidansteele** [comment]
It appears a hacky workaround is to :

* Specify `uses: docker//hello-world` for steps
* First step logs into private image repo and pulls private image
* Retag the private image as `hello-world`
* Later steps will now use the private image that isn't the real hello-world

Obviously this is pretty bad and dependent on current beta implementation details, but enough to unblock me (and anyone else reading this who is likewise stuck) for now.

**Comment by timruffles** [comment]
Thanks for reporting and supplying a workaround. I'll close this and pass on your feedback.

Thanks for beta-testing Actions ✨ !

**Comment by alpha-er** [comment]
Another workaround I find a bit cleaner specifically for ECR:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@master
      - name: image build
        env:
          ECR_REPO: account.dkr.ecr.region.amazonaws.com/my-ecr-repo
        run: docker build . -f Dockerfile -t $ECR_REPO
      - name: ecr push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: region
          ECR_REPO: account.dkr.ecr.region.amazonaws.com/my-ecr-repo
        uses: actions/aws/cli@master
        with:
          entrypoint: /bin/sh
          args: "-c \"aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION | sh && docker push $ECR_REPO\""
```
Overrides `actions/aws/cli`'s entrypoint and immediately pushing the image after `ecr get-login`.
