### ISSUE TITLE
Converted workflows/push.yml fails yaml linting

### ISSUE THREAD

**Issue by konstruktoid** [actions/migrate#39]
After converting to the new `.yaml` format, my action script that lints `.yaml` files failed.

- Shell/terminal output:

```sh
$ sh ./action-lint/entrypoint.sh 
.//.github/workflows/push.yml
  1:1       warning  missing document start "---"  (document-start)
  1:1       warning  truthy value should be true or false  (truthy)
  8:5       error    wrong indentation: expected 6 but found 4  (indentation)
```

Old:
```hcl
workflow "New workflow" {
  on = "push"
  resolves = ["Konstruktoid YAML lint"]
}

action "Konstruktoid YAML lint" {
  uses = "./action-lint"
}
```

Converted:
```yaml
on: push
name: New workflow
jobs:
  konstruktoidYAMLLint:
    name: Konstruktoid YAML lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Konstruktoid YAML lint
      uses: ./action-lint
```

Linted:
```yaml
on: push
name: New workflow
jobs:
  konstruktoidYAMLLint:
    name: Konstruktoid YAML lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Konstruktoid YAML lint
        uses: ./action-lint
```
